import type { LucideIcon } from "lucide-react";
import {
  Activity, AlarmClock, ArrowRight, BadgeCheck, Ban, BookOpen, Brain, Building2, Calendar, ChartBar, ChartLine, ChartPie, Check, CircleAlert, CircleCheck, CircleX, ClipboardCheck, ClipboardList, Clock, Cog, Coins, Compass, Cross, DollarSign, Droplets, Ear, Eye, EyeOff, Factory, FileText, Flag, Flame, Forklift, Frown, Glasses, Globe, GraduationCap, Hammer, Hand, HandHeart, Handshake, HardHat, HeartHandshake, HeartPulse, Hourglass, House, Key, Layers, Leaf, Lightbulb, Link, ListChecks, Lock, Mail, MapPin, Megaphone, Meh, MessageCircle, MessagesSquare, NotebookPen, OctagonAlert, Package, Percent, Phone, Pill, Puzzle, Receipt, Recycle, RefreshCw, Repeat, Rocket, ScanFace, Search, Settings, Shield, ShieldCheck, ShoppingCart, Siren, Smile, Sparkles, Star, Stethoscope, Store, Sun, Target, Thermometer, ThumbsDown, ThumbsUp, Timer, TrendingDown, TrendingUp, TriangleAlert, Trophy, Truck, User, UserCheck, Users, Wallet, Warehouse, Wind, Wrench, X, Zap,
} from "lucide-react";

/**
 * The icons a slide can show: the same curated names the server draws (keep in sync with
 * app/services/slides/icons.py in the backend). Each with its Spanish name for the picker.
 */
export const SLIDE_ICONS: { name: string; label: string; Icon: LucideIcon }[] = [
  { name: "trending-down", label: "A la baja", Icon: TrendingDown },
  { name: "activity", label: "Actividad", Icon: Activity },
  { name: "refresh-cw", label: "Actualizar", Icon: RefreshCw },
  { name: "handshake", label: "Acuerdo", Icon: Handshake },
  { name: "settings", label: "Ajustes", Icon: Settings },
  { name: "trending-up", label: "Al alza", Icon: TrendingUp },
  { name: "circle-alert", label: "Alerta", Icon: CircleAlert },
  { name: "heart-handshake", label: "Apoyo", Icon: HeartHandshake },
  { name: "flag", label: "Bandera", Icon: Flag },
  { name: "wallet", label: "Billetera", Icon: Wallet },
  { name: "warehouse", label: "Bodega", Icon: Warehouse },
  { name: "compass", label: "Brújula", Icon: Compass },
  { name: "search", label: "Buscar", Icon: Search },
  { name: "calendar", label: "Calendario", Icon: Calendar },
  { name: "truck", label: "Camión", Icon: Truck },
  { name: "lock", label: "Candado", Icon: Lock },
  { name: "layers", label: "Capas", Icon: Layers },
  { name: "shopping-cart", label: "Carrito", Icon: ShoppingCart },
  { name: "house", label: "Casa", Icon: House },
  { name: "hard-hat", label: "Casco", Icon: HardHat },
  { name: "brain", label: "Cerebro", Icon: Brain },
  { name: "rocket", label: "Cohete", Icon: Rocket },
  { name: "messages-square", label: "Conversación", Icon: MessagesSquare },
  { name: "circle-check", label: "Correcto", Icon: CircleCheck },
  { name: "mail", label: "Correo", Icon: Mail },
  { name: "cross", label: "Cruz", Icon: Cross },
  { name: "notebook-pen", label: "Cuaderno", Icon: NotebookPen },
  { name: "hand-heart", label: "Cuidado", Icon: HandHeart },
  { name: "alarm-clock", label: "Despertador", Icon: AlarmClock },
  { name: "sparkles", label: "Destellos", Icon: Sparkles },
  { name: "dollar-sign", label: "Dinero", Icon: DollarSign },
  { name: "file-text", label: "Documento", Icon: FileText },
  { name: "building-2", label: "Edificio", Icon: Building2 },
  { name: "zap", label: "Electricidad", Icon: Zap },
  { name: "cog", label: "Engranaje", Icon: Cog },
  { name: "link", label: "Enlace", Icon: Link },
  { name: "users", label: "Equipo", Icon: Users },
  { name: "x", label: "Equis", Icon: X },
  { name: "shield", label: "Escudo", Icon: Shield },
  { name: "stethoscope", label: "Estetoscopio", Icon: Stethoscope },
  { name: "star", label: "Estrella", Icon: Star },
  { name: "smile", label: "Feliz", Icon: Smile },
  { name: "arrow-right", label: "Flecha", Icon: ArrowRight },
  { name: "flame", label: "Fuego", Icon: Flame },
  { name: "factory", label: "Fábrica", Icon: Factory },
  { name: "glasses", label: "Gafas", Icon: Glasses },
  { name: "droplets", label: "Gotas", Icon: Droplets },
  { name: "graduation-cap", label: "Graduación", Icon: GraduationCap },
  { name: "chart-pie", label: "Gráfico circular", Icon: ChartPie },
  { name: "chart-bar", label: "Gráfico de barras", Icon: ChartBar },
  { name: "chart-line", label: "Gráfico de línea", Icon: ChartLine },
  { name: "leaf", label: "Hoja", Icon: Leaf },
  { name: "lightbulb", label: "Idea", Icon: Lightbulb },
  { name: "circle-x", label: "Incorrecto", Icon: CircleX },
  { name: "book-open", label: "Libro", Icon: BookOpen },
  { name: "clipboard-list", label: "Lista", Icon: ClipboardList },
  { name: "list-checks", label: "Lista de chequeo", Icon: ListChecks },
  { name: "clipboard-check", label: "Lista revisada", Icon: ClipboardCheck },
  { name: "key", label: "Llave", Icon: Key },
  { name: "wrench", label: "Llave inglesa", Icon: Wrench },
  { name: "hand", label: "Mano", Icon: Hand },
  { name: "hammer", label: "Martillo", Icon: Hammer },
  { name: "thumbs-up", label: "Me gusta", Icon: ThumbsUp },
  { name: "pill", label: "Medicamento", Icon: Pill },
  { name: "megaphone", label: "Megáfono", Icon: Megaphone },
  { name: "message-circle", label: "Mensaje", Icon: MessageCircle },
  { name: "coins", label: "Monedas", Icon: Coins },
  { name: "forklift", label: "Montacargas", Icon: Forklift },
  { name: "globe", label: "Mundo", Icon: Globe },
  { name: "meh", label: "Neutral", Icon: Meh },
  { name: "thumbs-down", label: "No me gusta", Icon: ThumbsDown },
  { name: "target", label: "Objetivo", Icon: Target },
  { name: "eye-off", label: "Oculto", Icon: EyeOff },
  { name: "eye", label: "Ojo", Icon: Eye },
  { name: "ear", label: "Oído", Icon: Ear },
  { name: "package", label: "Paquete", Icon: Package },
  { name: "octagon-alert", label: "Pare", Icon: OctagonAlert },
  { name: "triangle-alert", label: "Peligro", Icon: TriangleAlert },
  { name: "user", label: "Persona", Icon: User },
  { name: "user-check", label: "Persona verificada", Icon: UserCheck },
  { name: "percent", label: "Porcentaje", Icon: Percent },
  { name: "ban", label: "Prohibido", Icon: Ban },
  { name: "shield-check", label: "Protección", Icon: ShieldCheck },
  { name: "receipt", label: "Recibo", Icon: Receipt },
  { name: "recycle", label: "Reciclaje", Icon: Recycle },
  { name: "clock", label: "Reloj", Icon: Clock },
  { name: "hourglass", label: "Reloj de arena", Icon: Hourglass },
  { name: "repeat", label: "Repetir", Icon: Repeat },
  { name: "puzzle", label: "Rompecabezas", Icon: Puzzle },
  { name: "scan-face", label: "Rostro", Icon: ScanFace },
  { name: "heart-pulse", label: "Salud", Icon: HeartPulse },
  { name: "siren", label: "Sirena", Icon: Siren },
  { name: "sun", label: "Sol", Icon: Sun },
  { name: "phone", label: "Teléfono", Icon: Phone },
  { name: "timer", label: "Temporizador", Icon: Timer },
  { name: "thermometer", label: "Termómetro", Icon: Thermometer },
  { name: "store", label: "Tienda", Icon: Store },
  { name: "frown", label: "Triste", Icon: Frown },
  { name: "trophy", label: "Trofeo", Icon: Trophy },
  { name: "map-pin", label: "Ubicación", Icon: MapPin },
  { name: "badge-check", label: "Verificado", Icon: BadgeCheck },
  { name: "wind", label: "Viento", Icon: Wind },
  { name: "check", label: "Visto bueno", Icon: Check },
];

const BY_NAME = new Map(SLIDE_ICONS.map((icon) => [icon.name, icon]));

/** The icon with that name, or undefined (blank or not one the slides know). */
export function slideIcon(name: string | undefined) {
  return name ? BY_NAME.get(name) : undefined;
}
